"""add on_menu to categories

Revision ID: 67c92b445434
Revises: 91da931cbf24
Create Date: 2022-06-07 20:31:23.508474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c92b445434'
down_revision = '91da931cbf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('on_menu', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('categories', 'on_menu')
    # ### end Alembic commands ###
