"""add field active to stores

Revision ID: 757f154d28f0
Revises: 67c92b445434
Create Date: 2022-06-07 20:46:16.639002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757f154d28f0'
down_revision = '67c92b445434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'active')
    # ### end Alembic commands ###
