"""empty message

Revision ID: 91da931cbf24
Revises: 
Create Date: 2022-06-07 20:22:30.851935

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '91da931cbf24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
