"""update models

Revision ID: db1f4f087800
Revises: 757f154d28f0
Create Date: 2022-06-07 23:02:42.444061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1f4f087800'
down_revision = '757f154d28f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('stores', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('stores', 'is_active')
    # ### end Alembic commands ###
